products:
    css: div.a-section.a-spacing-medium
    multiple: true
    type: Text
    children:
        name:
            css: h2 span
            type: Text
        link:
            css: h2 a
            type: Attribute
            attribute: href
        price:
            css: div.a-section.a-spacing-none.a-spacing-top-small a.a-size-base.a-link-normal.a-text-normal > span.a-price > span.a-offscreen
            type: Text
        regular-price:
            css: div.a-section.a-spacing-none.a-spacing-top-small a.a-size-base.a-link-normal.a-text-normal >  span.a-text-price > span.a-offscreen
            type: Text